const DEFAULT_SHEET_TRIGGER_CLASSNAME = '_sheet-trigger'

const DEFAULT_SHEET_CLOSE_BUTTON_CLASSNAME = '_sheet-close-button absolute right-4 top-4 p-2'

const DEFAULT_SHEET_CLOSE_BUTTON_ICON_CLASSNAME = '_sheet-close-button-icon h-4 w-4 opacity-70'

export {
	DEFAULT_SHEET_CLOSE_BUTTON_CLASSNAME,
	DEFAULT_SHEET_CLOSE_BUTTON_ICON_CLASSNAME,
	DEFAULT_SHEET_TRIGGER_CLASSNAME,
}
