export * from '@/components/collapsible/components/collapsible'
export * from '@/components/collapsible/components/collapsible-content'
export * from '@/components/collapsible/components/collapsible-trigger'
export * from '@/components/collapsible/types/collapsible'
export * from '@/components/collapsible/types/collapsible-content'
export * from '@/components/collapsible/types/collapsible-trigger'
