const DEFAULT_COLLAPSIBLE_CONTENT_CLASSNAME = 'render-ui-collapsible-content'

const COLLAPSIBLE_ANIMATED_CONTENT_CLASSNAME =
  'data-[state=closed]:animate-collapsible-up data-[state=open]:animate-collapsible-down overflow-hidden'

const COLLAPSIBLE_CONTENT_DEFAULT_ANIMATION_DURATION = 200

export {
  DEFAULT_COLLAPSIBLE_CONTENT_CLASSNAME,
  COLLAPSIBLE_ANIMATED_CONTENT_CLASSNAME,
  COLLAPSIBLE_CONTENT_DEFAULT_ANIMATION_DURATION,
}
