const RIPPLE_ANIMATION_END_OPACITY = 0
const RIPPLE_ANIMATION_START_SCALE = 0
const RIPPLE_ANIMATION_END_DEFAULT_SCALE = 2

const RIPPLE_DEFAULT_OPACITY = 0.25
const RIPPLE_DEFAULT_DURATION_MULTIPLIER = 1
const RIPPLE_DEFAULT_SCALE_MULTIPLIER = 1

const RIPPLE_BASE_MULTIPLIER = 0.01
const RIPPLE_MIDDLE_DURATION = 0.25
const RIPPLE_SIZE_100 = 100
const RIPPLE_OVER_100_DURATION = 0.75
const RIPPLE_UNDER_100_DURATION = 0.675

const RIPPLE_RIPPLE_BASE_STYLE = {
  backgroundColor: 'current',
  position: 'absolute',
  borderRadius: '100%',
  transformOrigin: 'center',
  pointerEvents: 'none',
  zIndex: '0',
} as const

const KEYBOARD_RIPPLE_MUTATION_OBSERVER_OPTIONS = {
  attributes: true,
  attributeFilter: ['data-keyboard-pressed'],
}

export {
  KEYBOARD_RIPPLE_MUTATION_OBSERVER_OPTIONS,
  RIPPLE_ANIMATION_END_DEFAULT_SCALE,
  RIPPLE_ANIMATION_END_OPACITY,
  RIPPLE_ANIMATION_START_SCALE,
  RIPPLE_BASE_MULTIPLIER,
  RIPPLE_DEFAULT_DURATION_MULTIPLIER,
  RIPPLE_DEFAULT_OPACITY,
  RIPPLE_DEFAULT_SCALE_MULTIPLIER,
  RIPPLE_MIDDLE_DURATION,
  RIPPLE_OVER_100_DURATION,
  RIPPLE_RIPPLE_BASE_STYLE,
  RIPPLE_SIZE_100,
  RIPPLE_UNDER_100_DURATION,
}
